name: Deploy to cloudtype
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect repository
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hangeulmbti-backend
          yaml: |-
            name: hangeulmbti-backend
            app: dockerfile
            options:
              port: 8080
              dockerfile: Dockerfile
              git:
                branch: main
                url: https://github.com/LUNA-coding/hangeulMBTI-backend.git
              start: wget -O /app/firebase-adminkey.json ${{ secrets.FIREBASE_ADMINKEY_URL }} && python server.py